SG-1414 - use ghost inspector webhook for suite status

diff --git a/.circleci/scripts/tests/ghost-inspector/run-gi-suite b/.circleci/scripts/tests/ghost-inspector/run-gi-suite
--- a/.circleci/scripts/tests/ghost-inspector/run-gi-suite
+++ b/.circleci/scripts/tests/ghost-inspector/run-gi-suite
@@ -7,104 +7,110 @@ GI_START_URL="$MULTIDEV_SITE_URL"
 
 echo "Using start url: $GI_START_URL"
 
-# set up a couple variables to monitor result state
-STATUS='null'
-SUITE_RESULT=
-GI_PASSING=
+curl -X POST \
+    -H "Content-Type: application/json" \
+    -H "X-GitHub-Event: push" \
+    -d '{"payload": "{\"repository\": {\"statuses_url\": \"https://api.github.com/repos/'$GITHUB_ORG'/'$CIRCLE_PROJECT_REPONAME'/statuses/'$CIRCLE_SHA1'\"},\"sha\": \"<sha>\"}"}' \
+    "https://api.ghostinspector.com/v1/suites/$GI_SUITE_ADA/execute/?apiKey=$GI_API_KEY&startUrl=$GI_START_URL"
 
-EXECUTE_URL="https://api.ghostinspector.com/v1/suites/$GI_SUITE_ADA/execute?apiKey=$GI_API_KEY&startUrl=$GI_START_URL&immediate=1"
+# # set up a couple variables to monitor result state
+# STATUS='null'
+# SUITE_RESULT=
+# GI_PASSING=
 
-echo "Execute url: $EXECUTE_URL"
+# EXECUTE_URL="https://api.ghostinspector.com/v1/suites/$GI_SUITE_ADA/execute?apiKey=$GI_API_KEY&startUrl=$GI_START_URL&immediate=1"
 
-GI_RESULT_ID=$(curl -s $EXECUTE_URL | jq -r '.data._id')
+# echo "Execute url: $EXECUTE_URL"
 
-# Poll for the suite result, sleep for a few seconds if it hasn't changed
-echo "Polling for suite results (ID: $GI_RESULT_ID)"
-while [ "$STATUS" = 'null' ]; do
-  SUITE_RESULT=$(curl -s "https://api.ghostinspector.com/v1/suite-results/$GI_RESULT_ID/?apiKey=$GI_API_KEY")
-  RESPONSE_STATUS=$(echo $SUITE_RESULT | jq -r '.code')
-  if [ $? -ne 0 ] || [ "$RESPONSE_STATUS" == 'ERROR' ]; then # invalid json or api error, break
-    echo "API ERROR"
-    break
-  fi
-  STATUS=$(echo $SUITE_RESULT | jq -r '.data.passing')
-  echo " - status: $STATUS"
-  sleep 5
-done
+# GI_RESULT_ID=$(curl -s $EXECUTE_URL | jq -r '.data._id')
 
-# status has been updated, check results for "passing"
-if [ "$(echo $SUITE_RESULT | jq -r '.data.passing')" != 'true' ]; then
-  echo "Suite failed! ¯\_(ツ)_/¯"
-  GI_PASSING=1
-else 
-  echo "Suite passed! \o/"
-  GI_PASSING=0
-fi
+# # Poll for the suite result, sleep for a few seconds if it hasn't changed
+# echo "Polling for suite results (ID: $GI_RESULT_ID)"
+# while [ "$STATUS" = 'null' ]; do
+#   SUITE_RESULT=$(curl -s "https://api.ghostinspector.com/v1/suite-results/$GI_RESULT_ID/?apiKey=$GI_API_KEY")
+#   RESPONSE_STATUS=$(echo $SUITE_RESULT | jq -r '.code')
+#   if [ $? -ne 0 ] || [ "$RESPONSE_STATUS" == 'ERROR' ]; then # invalid json or api error, break
+#     echo "API ERROR"
+#     break
+#   fi
+#   STATUS=$(echo $SUITE_RESULT | jq -r '.data.passing')
+#   echo " - status: $STATUS"
+#   sleep 5
+# done
 
-SUITE_TESTS=$(curl -s "https://api.ghostinspector.com/v1/suites/$GI_SUITE/tests/?apiKey=$GI_API_KEY")
-GI_SUITE_TEST_RESULTS_SLACK=$(echo $SUITE_TESTS | jq -r '.data[] | if(.passing!=true) then ":redx: " elif (.screenshotComparePassing!=true) then ":orangedash: " elif(.passing) then ":greencheck: " else ":redx: " end + " \(.name)"')
+# # status has been updated, check results for "passing"
+# if [ "$(echo $SUITE_RESULT | jq -r '.data.passing')" != 'true' ]; then
+#   echo "Suite failed! ¯\_(ツ)_/¯"
+#   GI_PASSING=1
+# else 
+#   echo "Suite passed! \o/"
+#   GI_PASSING=0
+# fi
 
-if [ -n "$CIRCLE_PULL_REQUEST" ]; then
-  PR='<'$CIRCLE_PULL_REQUEST'|pr>'
-else
-  PR='`'$CIRCLE_BRANCH'`'
-fi
+# SUITE_TESTS=$(curl -s "https://api.ghostinspector.com/v1/suites/$GI_SUITE/tests/?apiKey=$GI_API_KEY")
+# GI_SUITE_TEST_RESULTS_SLACK=$(echo $SUITE_TESTS | jq -r '.data[] | if(.passing!=true) then ":redx: " elif (.screenshotComparePassing!=true) then ":orangedash: " elif(.passing) then ":greencheck: " else ":redx: " end + " \(.name)"')
 
-# output suite tests with results
-echo $SUITE_TESTS | jq -r '.data[] | if(.passing) then "\(.name): passed" else "\(.name): failed" end'
+# if [ -n "$CIRCLE_PULL_REQUEST" ]; then
+#   PR='<'$CIRCLE_PULL_REQUEST'|pr>'
+# else
+#   PR='`'$CIRCLE_BRANCH'`'
+# fi
 
-# pass some things along as env variables
-if [ -n "$CIRCLE_BRANCH" ]; then # circleci
-  echo 'export GI_START_URL="'$GI_START_URL'"' >> $BASH_ENV
-  echo 'export GI_RESULT_ID="'$GI_RESULT_ID'"' >> $BASH_ENV
-  echo 'export GI_SUITE_TEST_RESULTS_SLACK="'$GI_SUITE_TEST_RESULTS_SLACK'"' >> $BASH_ENV
-  echo 'export PR="'$PR'"' >> $BASH_ENV
-  echo 'export GI_PASSING="'$GI_PASSING'"' >> $BASH_ENV
-else # local
-  export GI_START_URL=$GI_START_URL
-  export GI_RESULT_ID=$GI_RESULT_ID
-  export GI_SUITE_TEST_RESULTS_SLACK=$GI_SUITE_TEST_RESULTS_SLACK
-  export GI_PASSING=$PASSING
-  export PR=$PR
-fi
+# # output suite tests with results
+# echo $SUITE_TESTS | jq -r '.data[] | if(.passing) then "\(.name): passed" else "\(.name): failed" end'
 
-title="<$GI_START_URL|$GI_START_URL> | $PR | <http://ronswanbot.herokuapp.com/ghost-inspector/suite-results/$GI_RESULT_ID|results>"
+# # pass some things along as env variables
+# if [ -n "$CIRCLE_BRANCH" ]; then # circleci
+#   echo 'export GI_START_URL="'$GI_START_URL'"' >> $BASH_ENV
+#   echo 'export GI_RESULT_ID="'$GI_RESULT_ID'"' >> $BASH_ENV
+#   echo 'export GI_SUITE_TEST_RESULTS_SLACK="'$GI_SUITE_TEST_RESULTS_SLACK'"' >> $BASH_ENV
+#   echo 'export PR="'$PR'"' >> $BASH_ENV
+#   echo 'export GI_PASSING="'$GI_PASSING'"' >> $BASH_ENV
+# else # local
+#   export GI_START_URL=$GI_START_URL
+#   export GI_RESULT_ID=$GI_RESULT_ID
+#   export GI_SUITE_TEST_RESULTS_SLACK=$GI_SUITE_TEST_RESULTS_SLACK
+#   export GI_PASSING=$PASSING
+#   export PR=$PR
+# fi
 
-data=$(printf '{
-  "attachments": [{
-    "fallback": "sfgov tests complete",
-    "blocks": [
-      {
-        "type": "section",
-        "text": {
-          "type": "mrkdwn",
-          "text": "%s"
-        }
-      },
-      {
-        "type": "divider"
-      },
-      {
-        "type": "section",
-        "text": {
-          "type": "mrkdwn",
-          "text": ":ghost: *e2e test results*\n%s"
-        }
-      },
-      {
-        "type": "divider"
-      },
-      {
-        "type": "section",
-        "text": {
-          "type": "mrkdwn",
-          "text": ":accessibility: *scan results*\n```%s```"
-        }
-      }
-    ]
-  }]
-}' "$title" "$GI_SUITE_TEST_RESULTS_SLACK" "accessibility scan results from gi here")
+# title="<$GI_START_URL|$GI_START_URL> | $PR | <http://ronswanbot.herokuapp.com/ghost-inspector/suite-results/$GI_RESULT_ID|results>"
 
-curl -g -X POST -H 'Content-type: application/json' --data "$data" $RONBOT_WEBHOOK_URL
+# data=$(printf '{
+#   "attachments": [{
+#     "fallback": "sfgov tests complete",
+#     "blocks": [
+#       {
+#         "type": "section",
+#         "text": {
+#           "type": "mrkdwn",
+#           "text": "%s"
+#         }
+#       },
+#       {
+#         "type": "divider"
+#       },
+#       {
+#         "type": "section",
+#         "text": {
+#           "type": "mrkdwn",
+#           "text": ":ghost: *e2e test results*\n%s"
+#         }
+#       },
+#       {
+#         "type": "divider"
+#       },
+#       {
+#         "type": "section",
+#         "text": {
+#           "type": "mrkdwn",
+#           "text": ":accessibility: *scan results*\n```%s```"
+#         }
+#       }
+#     ]
+#   }]
+# }' "$title" "$GI_SUITE_TEST_RESULTS_SLACK" "accessibility scan results from gi here")
 
-exit $GI_PASSING
+# curl -g -X POST -H 'Content-type: application/json' --data "$data" $RONBOT_WEBHOOK_URL
+
+# exit $GI_PASSING
