bring back polling

diff --git a/.circleci/scripts/tests/ghost-inspector/run-gi-suite b/.circleci/scripts/tests/ghost-inspector/run-gi-suite
--- a/.circleci/scripts/tests/ghost-inspector/run-gi-suite
+++ b/.circleci/scripts/tests/ghost-inspector/run-gi-suite
@@ -7,45 +7,49 @@ GI_START_URL="$MULTIDEV_SITE_URL"
 
 echo "Using start url: $GI_START_URL"
 
-curl -X POST \
+# set up a couple variables to monitor result state
+STATUS='null'
+SUITE_RESULT=
+GI_PASSING=
+
+GI_RESULT_ID=$(curl -X POST \
     -H "Content-Type: application/json" \
     -H "X-GitHub-Event: push" \
     -d '{"payload": "{\"repository\": {\"statuses_url\": \"https://api.github.com/repos/'$GITHUB_ORG'/'$CIRCLE_PROJECT_REPONAME'/statuses/'$CIRCLE_SHA1'\"},\"sha\": \"'$CIRCLE_SHA1'\"}"}' \
-    "https://api.ghostinspector.com/v1/suites/$GI_SUITE_ADA/execute/?apiKey=$GI_API_KEY&startUrl=$GI_START_URL&immediate=0"
+    "https://api.ghostinspector.com/v1/suites/$GI_SUITE_ADA/execute/?apiKey=$GI_API_KEY&startUrl=$GI_START_URL&immediate=1")
 
-# # set up a couple variables to monitor result state
-# STATUS='null'
-# SUITE_RESULT=
-# GI_PASSING=
+# Poll for the suite result, sleep for a few seconds if it hasn't changed
+# Ghost Inspector currently does not support webhook for when an entire suite has finished executing, only for indidiviual tests within a suite
+echo "Polling for suite results (ID: $GI_RESULT_ID)"
+while [ "$STATUS" = 'null' ]; do
+  SUITE_RESULT=$(curl -s "https://api.ghostinspector.com/v1/suite-results/$GI_RESULT_ID/?apiKey=$GI_API_KEY")
+  RESPONSE_STATUS=$(echo $SUITE_RESULT | jq -r '.code')
+  if [ $? -ne 0 ] || [ "$RESPONSE_STATUS" == 'ERROR' ]; then # invalid json or api error, break
+    echo "API ERROR"
+    break
+  fi
+  STATUS=$(echo $SUITE_RESULT | jq -r '.data.passing')
+  echo " - status: $STATUS"
+  sleep 5
+done
 
-# EXECUTE_URL="https://api.ghostinspector.com/v1/suites/$GI_SUITE_ADA/execute?apiKey=$GI_API_KEY&startUrl=$GI_START_URL&immediate=1"
+# status has been updated, check results for "passing"
+if [ "$(echo $SUITE_RESULT | jq -r '.data.passing')" != 'true' ]; then
+  echo "Suite failed! ¯\_(ツ)_/¯"
+  GI_PASSING=1
+else 
+  echo "Suite passed! \o/"
+  GI_PASSING=0
+fi
 
-# echo "Execute url: $EXECUTE_URL"
+SHORT_SHA=$(echo $CIRCLE_SHA1 | cut -c -7)
+PR_NUMBER=$(echo https://github.com/SFDigitalServices/sfgov/pull/1010 | awk -F "/" '{print $NF}')
 
-# GI_RESULT_ID=$(curl -s $EXECUTE_URL | jq -r '.data._id')
+THREAD_TS=$(curl -H "Authorization: Bearer $SLACK_USER_TOKEN" "https://slack.com/api/search.messages?query=$PR_NUMBER%20$SHORT_SHA%20in%3A%23proj-sfdotgov-eng&sort=timestamp&pretty=1" | jq .messages.matches[0].ts)
 
-# # Poll for the suite result, sleep for a few seconds if it hasn't changed
-# echo "Polling for suite results (ID: $GI_RESULT_ID)"
-# while [ "$STATUS" = 'null' ]; do
-#   SUITE_RESULT=$(curl -s "https://api.ghostinspector.com/v1/suite-results/$GI_RESULT_ID/?apiKey=$GI_API_KEY")
-#   RESPONSE_STATUS=$(echo $SUITE_RESULT | jq -r '.code')
-#   if [ $? -ne 0 ] || [ "$RESPONSE_STATUS" == 'ERROR' ]; then # invalid json or api error, break
-#     echo "API ERROR"
-#     break
-#   fi
-#   STATUS=$(echo $SUITE_RESULT | jq -r '.data.passing')
-#   echo " - status: $STATUS"
-#   sleep 5
-# done
+echo $THREAD_TS
 
-# # status has been updated, check results for "passing"
-# if [ "$(echo $SUITE_RESULT | jq -r '.data.passing')" != 'true' ]; then
-#   echo "Suite failed! ¯\_(ツ)_/¯"
-#   GI_PASSING=1
-# else 
-#   echo "Suite passed! \o/"
-#   GI_PASSING=0
-# fi
+exit $GI_PASSING
 
 # SUITE_TESTS=$(curl -s "https://api.ghostinspector.com/v1/suites/$GI_SUITE/tests/?apiKey=$GI_API_KEY")
 # GI_SUITE_TEST_RESULTS_SLACK=$(echo $SUITE_TESTS | jq -r '.data[] | if(.passing!=true) then ":redx: " elif (.screenshotComparePassing!=true) then ":orangedash: " elif(.passing) then ":greencheck: " else ":redx: " end + " \(.name)"')
